# Generated by Django 2.1.1 on 2018-09-18 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='email',
        ),
        migrations.AddField(
            model_name='competitor',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='competition',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
