# Generated by Django 2.1.1 on 2018-09-18 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20180918_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
