# Generated by Django 2.1.1 on 2018-09-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20180918_2215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='competition',
        ),
    ]
