# Generated by Django 2.1.1 on 2018-09-18 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20180918_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
