# Generated by Django 2.1.1 on 2018-09-18 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20180918_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='competitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Competitor'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='reg_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Regulatory'),
        ),
    ]
