# Generated by Django 2.1.1 on 2018-09-18 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20180918_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulatory',
            name='content',
            field=models.TextField(db_column='Treść'),
        ),
        migrations.AlterField(
            model_name='regulatory',
            name='created_date',
            field=models.DateTimeField(db_column='Utworzono', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='regulatory',
            name='name',
            field=models.CharField(blank=True, db_column='Nazwa', max_length=200),
        ),
        migrations.AlterField(
            model_name='regulatory',
            name='published_date',
            field=models.DateTimeField(blank=True, db_column='Opublikowano', null=True),
        ),
    ]
