# Generated by Django 2.1.1 on 2018-09-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20180918_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulatory',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nazwa'),
        ),
    ]
