# Generated by Django 2.1.1 on 2018-09-19 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20180918_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'Zawody', 'verbose_name_plural': 'Zawody'},
        ),
        migrations.AlterModelOptions(
            name='competitor',
            options={'verbose_name': 'Zawodnik', 'verbose_name_plural': 'Zawodnicy'},
        ),
        migrations.AlterModelOptions(
            name='regulatory',
            options={'ordering': ('published_date',), 'verbose_name': 'Regulamin', 'verbose_name_plural': 'Regulaminy'},
        ),
        migrations.RemoveField(
            model_name='competition',
            name='competitor',
        ),
        migrations.AddField(
            model_name='competitor',
            name='comp_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Competition', verbose_name='Zawody'),
        ),
    ]
