# Generated by Django 2.1.1 on 2018-09-19 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_competitor_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ('name',), 'verbose_name': 'Zawody', 'verbose_name_plural': 'Zawody'},
        ),
        migrations.AlterField(
            model_name='competition',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='reg_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Regulatory', verbose_name='Regulamin'),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='gender',
            field=models.IntegerField(choices=[('1', 'Mężczyzna'), ('2', 'Kobieta')], default='1', verbose_name='Płeć'),
        ),
    ]
