# Generated by Django 2.1.1 on 2018-09-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_competition_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Info'),
        ),
    ]
