# Generated by Django 2.1.1 on 2018-09-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_competition_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='status',
            field=models.BooleanField(default='0', verbose_name='Status'),
        ),
    ]
