# Generated by Django 2.1.1 on 2018-09-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0020_competition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.BooleanField(choices=[('1', 'True'), ('0', 'False')], default='0', verbose_name='Status'),
        ),
    ]
