# Generated by Django 2.1.1 on 2018-09-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0021_auto_20180919_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.SmallIntegerField(choices=[('1', 'Aktywny'), ('0', 'Nieaktywny')]),
        ),
    ]
