# Generated by Django 2.1.1 on 2018-09-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0023_auto_20180919_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='comp_reported',
            field=models.IntegerField(blank='True', default='0', null=True, verbose_name='Zgłoszonych'),
        ),
    ]
