# Generated by Django 2.1.1 on 2018-09-20 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0025_auto_20180919_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_registered', models.DateTimeField()),
                ('start_number', models.IntegerField(default='0', verbose_name='Numer startowy')),
            ],
            options={
                'verbose_name': 'Zgłoszenie na bieg',
                'verbose_name_plural': 'Zgłoszenia na bieg',
                'ordering': ['time_registered'],
            },
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ('status',), 'verbose_name': 'Zawody', 'verbose_name_plural': 'Zawody'},
        ),
        migrations.AlterField(
            model_name='competitor',
            name='gender',
            field=models.IntegerField(choices=[('1', 'Mężczyzna'), ('2', 'Kobieta')], default='0', verbose_name='Płeć'),
        ),
        migrations.AddField(
            model_name='competitionregister',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Competition', verbose_name='Zawody'),
        ),
        migrations.AddField(
            model_name='competitionregister',
            name='competitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Competitor', verbose_name='Zawodnik'),
        ),
        migrations.AlterUniqueTogether(
            name='competitionregister',
            unique_together={('competition', 'competitor', 'start_number')},
        ),
    ]
