# Generated by Django 2.1.1 on 2018-09-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0027_auto_20180920_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Mężczyzna'), (2, 'Kobieta')], default=0, verbose_name='Płeć'),
        ),
    ]
