# Generated by Django 2.1.1 on 2018-09-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0028_auto_20180920_1605'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitionregister',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='competitionregister',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='competitionregister',
            name='competitor',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='username',
        ),
        migrations.AlterField(
            model_name='competitor',
            name='birth',
            field=models.DateField(verbose_name='Data urodzenia'),
        ),
        migrations.DeleteModel(
            name='CompetitionRegister',
        ),
    ]
