# Generated by Django 2.1.1 on 2018-09-21 07:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0029_auto_20180921_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulatory',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Treść regulaminu'),
        ),
    ]
