# Generated by Django 2.1.1 on 2018-09-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0030_auto_20180921_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='city',
            field=models.CharField(default='foobar', max_length=200, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Mężczyzna'), (2, 'Kobieta')], default=0, verbose_name='Płeć'),
        ),
    ]
