# Generated by Django 2.1.1 on 2018-09-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0031_auto_20180921_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='city',
            field=models.CharField(default=' ', max_length=200, verbose_name='Miasto'),
        ),
    ]
