# Generated by Django 2.1.1 on 2018-09-21 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0032_auto_20180921_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'BRAK'), (1, 'OK')], default=0)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='register.Competition')),
                ('competitor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='register.Competitor')),
            ],
        ),
    ]
