# Generated by Django 2.1.1 on 2018-09-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0034_auto_20180922_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='payment',
            field=models.SmallIntegerField(choices=[(0, 'BRAK'), (1, 'OK')], default=0, verbose_name='Płatności'),
        ),
    ]
