# Generated by Django 2.1.1 on 2018-09-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0035_auto_20180922_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='start_number',
            field=models.IntegerField(null=True, verbose_name='Numer startowy'),
        ),
    ]
