# Generated by Django 2.1.1 on 2018-09-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0036_auto_20180922_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='start_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numer startowy'),
        ),
    ]
