# Generated by Django 2.1.1 on 2018-09-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0037_auto_20180922_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='payment_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data płatności'),
        ),
    ]
