# Generated by Django 2.1.1 on 2018-09-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0039_remove_competitor_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data płatności'),
        ),
    ]
