# Generated by Django 2.1.1 on 2018-09-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0040_competitor_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='city',
            field=models.CharField(max_length=200, verbose_name='Miasto'),
        ),
    ]
