# Generated by Django 2.1.1 on 2018-09-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0041_auto_20180922_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='published_cate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='image',
            field=models.ImageField(blank='True', upload_to='events', verbose_name='Zdjęcie'),
        ),
    ]
