# Generated by Django 2.1.1 on 2018-09-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0042_auto_20180922_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='published_cate',
            new_name='published_date',
        ),
    ]
