# Generated by Django 2.1.1 on 2018-09-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0043_auto_20180922_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ('published_date',), 'verbose_name': 'Zawody', 'verbose_name_plural': 'Zawody'},
        ),
    ]
