# Generated by Django 2.1.1 on 2018-09-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0044_auto_20180922_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ('-id',), 'verbose_name': 'Zawody', 'verbose_name_plural': 'Zawody'},
        ),
        migrations.AlterModelOptions(
            name='competitor',
            options={'ordering': ['-id'], 'verbose_name': 'Zawodnik', 'verbose_name_plural': 'Zawodnicy'},
        ),
        migrations.RemoveField(
            model_name='competition',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='competitor',
            name='start_number',
            field=models.IntegerField(verbose_name='Numer startowy'),
        ),
    ]
