# Generated by Django 2.1.1 on 2018-09-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0045_auto_20180922_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Zawody sportowe'), (2, 'Inne wydarzenie')], default=0, verbose_name='Typ'),
        ),
    ]
