# Generated by Django 2.1.1 on 2018-09-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0046_competition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='start_number',
            field=models.IntegerField(blank=True, verbose_name='Numer startowy'),
        ),
    ]
