# Generated by Django 2.1.1 on 2018-09-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0048_auto_20180922_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='start_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Numer startowy'),
        ),
    ]
