# Generated by Django 2.1.1 on 2018-09-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0049_auto_20180922_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='start_number',
        ),
    ]
