# Generated by Django 2.1.1 on 2018-09-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0050_remove_competitor_start_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='type',
        ),
        migrations.AddField(
            model_name='competitor',
            name='start_number',
            field=models.IntegerField(default=0, verbose_name='Numer startowy'),
        ),
    ]
