# Generated by Django 2.1.1 on 2018-09-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0051_auto_20180922_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='payment',
            field=models.SmallIntegerField(choices=[(0, 'BRAK'), (1, 'OK')], default=0, verbose_name='Płatność'),
        ),
    ]
